server:
  port: 9090
  servlet:
    context-path: /theta
spring:
  datasource:
    url: jdbc:mariadb://localhost:${DATABASE_PORT:3306}/${DATABASE_NAME:gs_springboot}
    username: ${DATABASE_USER:root}
    password: ${DATABASE_PASSWORD:1xylixmaF7b7rTYqqQ2Q}
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      maximum-pool-size: 5
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true